site_name: "Diffusers-Interpret"
site_description: "Model explainer tool built on top of the 🤗 Diffusers library"
repo_name: "JoaoLages/diffusers-interpret"
repo_url: "https://github.com/JoaoLages/diffusers-interpret"

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src/diffusers_interpret]
  - search

watch:
  - src/diffusers_interpret

nav:
  - index.md
  - API:
    - Explainer: api/explainer.md
  - tutorials.md
  - how-to-guides.md
  - reference.md
  - explanation.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.tasklist:
      custom_checkbox: true