name: automatically deploy mkdocs site 
on:
  push:
    branches:
      - master 
      - main
      - mkdocs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs "mkdocstrings[python]" mkdocs-material 
      - run: mkdocs gh-deploy --force
